import Head from 'next/head'
import Homepage from '@/Components/Homepage'
import About from '@/Components/About'
import Project from '@/Components/Projects'
import Services from '@/Components/Services'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Homepage/>
        <About/>
        <Services/>
        <Project/>
        
      </main>
    </>
  )
}
